export {default as Footer} from "./Footer";
export {default as Home} from "../routes/Home";
export {default as Login} from "../routes/Login";
export {default as Navbar} from "./Navbar";
export {default as AdaugaPacient} from "../routes/Adauga_Pacient";
export {default as Register} from "../routes/Register";
export {default as Dashboard} from "../routes/Dashboard";
export {default as SignaturePad} from "../assets/SignaturePad";
export {default as CovidChestionar} from "../routes/CovidChestionar";
export {default as ResetPassword} from "../routes/Reset_passwod";
export {default as Calendar } from "./calendar";
